Improve Server
hive-engine/ssc_tokens_history pull request #28
Opened 2023-12-10 03:04 UTC by Rishi556

move validation of offset and limit to a middleware 
Add support for lookups by afterID which can prevent high ram usage from high offset 
Better logging

2024-01-27 01:59 UTC, bt-cryptomancer requested changes
Can you add some comments explaining what the morgan package is for?  Also provide an example of what a log line will look like when logging is enabled.  I'd like to see how it compares to the log output now.

Before approving this, one requirement I have is that the log output must show the `process.env.NODE_APP_INSTANCE` in some manner.  The account history server ran by the Engine team has this setup with the server process running in cluster mode to support 24 parallel instances, and I find it useful to see which instance processed a particular request to ensure that the load balancing is working as expected.

2024-01-27 02:55 UTC, Rishi556 commented
Here's an example line:

```
1|hscHisto | 2024-01-27T02:51:52: GET | - | /accountHistory?account=golem.overlord&limit=500&offset=0 | 2001:db8::1 | 2.03 ms | {"account":"golem.overlord","limit":500,"offset":0}
```

Morgan just made getting the data from the request easier. I added this while Hive-Engine was under attack and I didn't have too much time on my hands to debug, and was just the quickest way I saw rather than writing a custom middleware. Adding the app instance will be an easy change I can get done. For testing purposes, I assume you are starting using `pm2 start X -i 24`?

2024-01-28 02:12 UTC, bt-cryptomancer commented
Okay makes sense and seems like a good approach.  The log format is fine, so just needs to have the app instance added.

> For testing purposes, I assume you are starting using `pm2 start X -i 24`?

I have an `ecosystem.config.js` file for starting up the processes with pm2, with the following contents (which is basically an equivalent method of doing it):

```
module.exports = {
  apps : [{
    name: 'parser',
    script: 'parser.js',
    cwd: 'ssc_tokens_history/',
    watch: false,
    exp_backoff_restart_delay: 1000,
    log_file: '../logs/parser.log',
    time: true
  },
  {
    name: 'server',
    script: 'server.js',
    instances: "max",
    cwd: 'ssc_tokens_history/',
    watch: false,
    exp_backoff_restart_delay: 1000,
    log_file: '../logs/server.log',
    time: true,
    exec_mode : "cluster"
  }],
};
```

2024-01-28 02:16 UTC, bt-cryptomancer commented
One other question:  why did the package-lock.json file change to `"lockfileVersion": 3` ?  Does this imply that a certain minimum version of Node must be used to support the morgan package?

2024-01-28 02:33 UTC, Rishi556 commented
Thanks for the pm2 file, i'll get that added and tested. As for the lockfile version, that's a `npm` thing. lockfile version 3 is compatible with npm version 7+. npm v7 was shipped with node15 back in 2020, so upgrading is probably the best move. I'm using 
```
root@kc1:~# node -v
v18.19.0
root@kc1:~# npm -v
10.2.3
```

on my history node(and for local development) and it's why the lockfile version changed.

2025-03-21 17:36 UTC, closed without merging